### PR TITLE
Fix auto-complete error

### PR DESCRIPTION
**Pull request by russtoku**
This addresses issue #8

### CODE REVIEW

**Comment by jhamrick** [comment]
Thanks for the PR, but I would prefer to merge a fix that addresses the issue rather than just disabling it.

**Comment by russtoku** [comment]
I'm a noob to Emacs so I'm guessing that it's OK to remove ac-source-pycomplete because it doesn't look like the python-mode package is being used. I didn't see it in the .emacs.d/el-get directory.

**Comment by victl** [comment]
removing ac-source-pycomplete does make auto-complete working. But it seemed not providing any python related content.
And I keep it, I still get that same error. So confused...

**Comment by victl** [comment]
Well, I've finally come up with a solution.
For auto-completion, the pycomplete stuffs, and related pymacs, ropemacs are all not so good according to this article: [Jedi: A completion library for Python](https://www.masteringemacs.org/article/jedi-completion-library-python)
Follow that article to this [link](http://tkf.github.io/emacs-jedi/released/), you just need to add these lines to 'settings/python-settings.el':
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:setup-keys t)                      ; optional
(setq jedi:complete-on-dot t)                 ; optional
And everything works like a charm!

**Comment by victl** [comment]
Oh, don't forget to delete the 'ac-source-pycomplete' hacks in auto-complete-settings.el. They are just out-dated

**Comment by ehrenbrav** [comment]
Hi victl - this did *not* solve the issue for me. I deleted my old .emacs and .emacs.d/, ran boostrap.sh and everything worked fine, except upon the first character I type when starting emacs, I get the "auto-complete error: (void-variable ac-source-pycomplete)" message. I tried adding the lines you mentioned above and this did not solve the issue. I'm at a bit of a loss as to what could be causing this issue...I verified I have jedi, epc, and pylint installed both for python2.7 and python3... Any other ideas?

**Comment by victl** [comment]
see my second comment:

don't forget to delete the 'ac-source-pycomplete' hacks in auto-complete-settings.el. They are just out-dated

**Comment by ehrenbrav** [comment]
Got it - that solved the problem! I thought your comment was referring to hacks that you yourself had put in and not what was in the master branch...thanks for fixing this - I've been working on it for a good two hours or so...

I bought the book you mention above - I'm realizing I really ought to invest the time to learn how to use emacs properly (despite having used it already for years)...

**Pull request closed without merging**
